export const SOCKET_EVENTS = {
  FINDING_MATCH: 'finding_match',
  HERO_SELECTED: 'hero_selected',
  MATCH_FOUND: 'match_found',
  QUIT_QUEUE: 'quit_queue',
  SELECTION_COMPLETE: 'selection_complete',
  START_GAME: 'start_game',
  NEXT_TURN: 'next_turn',
  NEXT_TURN_REQUEST: 'next_turn_request',
  GAME_FINISHED_REQUEST: 'game_finished_request',
  GAME_FINISHED: 'game_finished',
  HERO_MOVED: 'hero_moved',
  HERO_MOVE_REQUEST: 'hero_move_request',
  HERO_ATTACKED: 'hero:attacked',
  HERO_ATTACK_REQUEST: 'hero_attack_request',
  HERO_COUNTER_ATTACK: 'hero:counter-attack',
  HERO_COUNTER_ATTACK_REQUEST: 'hero_counter_attack_request',
  UPDATE_GAME_STATE: 'update_game_state',
  SYNC_GAME_STATE: 'sync_game_state',
  RECONNECTING_PLAYER: 'reconnecting_player',
  TURN_TIMER_TICK: 'turn_timer_tick',
  TURN_TIMEOUT: 'turn_time_out',
  RETURN_TO_MATCH_ONLINE: 'return_to_match_online',
  HERO_SELECTION_TIMEOUT: 'hero_selection_timeout',
  HERO_SELECTION_TICK: 'hero_selection_tick'
};