name: Hero Tactic Game Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ vars.REMOTE_PORT }}
          script: |
            cd domains/kaiquenocetti.com/public_html/hero-tactics/

            # Apagar apenas arquivos de frontend antigos
            rm -rf assets favicon.ico index.html tactics-game

            git clone --depth=1 https://github.com/KaiqueNo7/tactics-game.git

            cd tactics-game
            npm install
            npm run build

            # Voltar para a pasta pública
            cd ..

            # Copiar novos arquivos da build
            cp -R tactics-game/dist/* .

            # (Opcional) Apagar node_modules para não ocupar espaço
            rm -rf tactics-game
