name: Hero Tactic Game Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./tactics-game # caso o projeto esteja numa subpasta

      - name: Build project
        run: npm run build
        working-directory: ./tactics-game

      - name: Prepare build for deployment
        run: ls -la tactics-game/dist

      - name: Deploy build to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ vars.REMOTE_PORT }}
          source: "tactics-game/dist/*"
          target: "/domains/kaiquenocetti.com/public_html/hero-tactics/"

      - name: Clean old files on server (optional)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ vars.REMOTE_PORT }}
          script: |
            cd domains/kaiquenocetti.com/public_html/hero-tactics/
            # Se quiser garantir que só ficam os arquivos novos:
            find . -maxdepth 1 ! -name 'dist' ! -name '.' -exec rm -rf {} +
